import jsPDF from 'jspdf';
import type { Conversation } from '@/types';
import { formatDate } from './format';

export function exportConversationToPDF(conversation: Conversation) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const maxWidth = pageWidth - 2 * margin;
  let yPosition = margin;

  // Helper function to add page if needed
  const checkPageBreak = (requiredSpace: number) => {
    if (yPosition + requiredSpace > pageHeight - margin) {
      doc.addPage();
      yPosition = margin;
      return true;
    }
    return false;
  };

  // Helper function to wrap text
  const wrapText = (text: string, maxWidth: number, fontSize: number): string[] => {
    doc.setFontSize(fontSize);
    return doc.splitTextToSize(text, maxWidth);
  };

  // Title
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('Chat Conversation Report', margin, yPosition);
  yPosition += 12;

  // Conversation metadata
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100);
  doc.text(`Title: ${conversation.title}`, margin, yPosition);
  yPosition += 6;
  doc.text(`Date: ${formatDate(conversation.created_at)}`, margin, yPosition);
  yPosition += 6;
  doc.text(`Messages: ${conversation.messages.length}`, margin, yPosition);
  yPosition += 15;

  // Draw separator line
  doc.setDrawColor(200);
  doc.line(margin, yPosition, pageWidth - margin, yPosition);
  yPosition += 10;

  // Messages
  conversation.messages.forEach((message, index) => {
    checkPageBreak(30);

    // Message header
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0);

    if (message.role === 'user') {
      doc.setTextColor(59, 130, 246); // Blue for user
      doc.text('You:', margin, yPosition);
    } else {
      doc.setTextColor(16, 185, 129); // Green for assistant
      doc.text('AI Assistant:', margin, yPosition);
    }
    yPosition += 7;

    // Message content
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(50);
    doc.setFontSize(10);

    const lines = wrapText(message.content, maxWidth, 10);
    lines.forEach((line: string) => {
      checkPageBreak(6);
      doc.text(line, margin, yPosition);
      yPosition += 5;
    });

    // Sources (if available)
    if (message.role === 'assistant' && message.sources && message.sources.length > 0) {
      yPosition += 3;
      checkPageBreak(15);

      doc.setFontSize(9);
      doc.setTextColor(100);
      doc.text('Sources:', margin, yPosition);
      yPosition += 5;

      message.sources.forEach((source) => {
        checkPageBreak(5);
        doc.text(`  • ${source.filename}`, margin + 5, yPosition);
        yPosition += 4;
      });
    }

    yPosition += 8;

    // Light separator between messages
    if (index < conversation.messages.length - 1) {
      doc.setDrawColor(230);
      doc.line(margin, yPosition, pageWidth - margin, yPosition);
      yPosition += 8;
    }
  });

  // Footer on last page
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(
      `Page ${i} of ${totalPages}`,
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' }
    );
    doc.text(
      'Generated by TechStore AI Support',
      pageWidth / 2,
      pageHeight - 5,
      { align: 'center' }
    );
  }

  // Save the PDF
  const filename = `conversation-${conversation.id}-${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(filename);
}
